//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_controledeponto
    {
        public int id_controleDePonto { get; set; }
        public int id_funcionario { get; set; }
        public Nullable<System.DateTime> dt_chegada { get; set; }
        public Nullable<System.DateTime> dt_saidaAlmoco { get; set; }
        public Nullable<System.DateTime> dt_voltaAlmoco { get; set; }
        public Nullable<System.DateTime> dt_saida { get; set; }
    
        public virtual tb_funcionario tb_funcionario { get; set; }
    }
}
