//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_compra_item
    {
        public int id_compra_item { get; set; }
        public int id_compra { get; set; }
        public int id_produto { get; set; }
    
        public virtual tb_compra tb_compra { get; set; }
        public virtual tb_produto tb_produto { get; set; }
    }
}
