//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp15.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_recuperacao
    {
        public int id_recuperacao { get; set; }
        public int id_usuario { get; set; }
        public string ds_codigo { get; set; }
        public System.DateTime dt_data { get; set; }
        public bool bt_usado { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
